# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'quupe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quupe
  pod 'Firebase/CoreOnly'
  pod 'Firebase/Auth'

  target 'quupe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'quupeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'quupe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for quupe-tvOS

end
